import 'dart:math';
import 'move_analysis.dart';

class CommentaryGenerator {
  static final _random = Random();

  static final Map<MoveCategory, List<String>> _templates = {
    MoveCategory.best: [
      "Tầm nhìn của một Đại kiện tướng! {played_move} chính xác là những gì Stockfish đề xuất.",
      "Bạn đã đánh một nước cờ hoàn hảo. {played_move} không thể chê vào đâu được.",
      "Một lựa chọn như sách giáo khoa! {played_move} là đáp án tốt nhất.",
      "Thật đáng kinh ngạc, {played_move} là nước đi sắc bén nhất trong lịch sử bàn cờ này.",
      "Nước đi {played_move} thể hiện trình độ chiến thuật tuyệt đỉnh của bạn.",
      "Không ai có thể tìm ra nước tốt hơn {played_move} ở thời điểm này.",
      "Một pha dứt điểm lạnh lùng, {played_move} chính là sự khác biệt giữa thắng và thua.",
      "Ngay cả máy tính cũng phải nể phục nước đi {played_move} của bạn.",
      "Bạn đã đọc vị đối thủ. {played_move} chính là bước ngoặt quyết định.",
      "Quá xuất sắc! {played_move} là lựa chọn tối ưu theo phân tích sâu.",
      "Sự tính toán của bạn ở {played_move} là hoàn toàn không có lỗ hổng.",
      "Tuyệt cú mèo! {played_move} đã khoá chặt một lợi thế lớn.",
      "Một phong cách thi đấu đỉnh cao được thể hiện qua nước {played_move}.",
      "Stockfish cũng gật gù với nước đi {played_move} của bạn.",
      "Chỉ có thiên tài mới đi {played_move} trong thế cờ căng thẳng thế này.",
      "Rất dứt khoát! {played_move} đi đúng vào điểm yếu của đối phương.",
      "{played_move} là một tuyệt tác nghệ thuật phòng ngự phản công.",
      "Không hề nao núng, {played_move} là quyết định vô cùng sáng suốt.",
      "Nước cờ {played_move} vừa giải nguy vừa đe dọa mạnh mẽ.",
      "Rất thông minh. {played_move} tối ưu hóa hoàn toàn vị trí các quân.",
      "Người máy cũng không đi hay hơn bạn ở nước {played_move} này.",
      "Điều tuyệt vời nhất ở {played_move} là tầm nhìn chiến lược sâu rộng.",
      "Hoàn hảo 100%. Nước {played_move} kiểm soát hoàn toàn trung tâm.",
      "Với {played_move}, bạn đã làm chủ ván đấu này.",
      "Bạn đã nhắm trúng tử huyệt. {played_move} là mũi dao đoạt mạng.",
      "Quá chính xác! Từng mili mét đều được tính toán trong {played_move}.",
      "Bạn đi {played_move} cứ như một kỳ thủ có hệ số Elo 3000 vậy.",
      "Đẳng cấp là mãi mãi. {played_move} khẳng định sức mạnh của bạn.",
      "Không thể tìm một vết xước trong cách bạn đi {played_move}.",
      "Đối thủ sẽ phải đau đầu với nước đi {played_move} đầy uy lực này.",
      "Sự kết hợp hoàn hảo giữa tấn công và phòng ngự qua {played_move}.",
      "Bạn nắm bắt thời cơ cực kỳ tuyệt vời bằng nước {played_move}.",
      "Đó mới là cờ vua! {played_move} khiến cục diện rẽ sang một hướng hoàn toàn có lợi.",
      "Siêu phẩm! Nước cờ {played_move} sẽ lưu danh sử sách.",
      "Rất tinh tế. Bạn đi {played_move} mà đối phương không thể lường trước.",
      "Thật khó để tin con người có thể phát hiện nước {played_move} sắc sảo đến vậy.",
      "Thế trận này chỉ chờ đợi một cú đấm như {played_move}.",
      "Nước đi {played_move} dọn đường cho hàng loạt mưu đồ vĩ đại phía sau.",
      "Chính xác và hiệu quả. Không có một lựa chọn nào hay hơn {played_move}.",
      "{played_move} - đơn giản mà đầy tính sát thương."
    ],
    MoveCategory.excellent: [
      "Một nước đi tuyệt vời! {played_move} rất đáng khen ngợi.",
      "Không phải là tốt nhất nhưng {played_move} là một lựa chọn hạng A.",
      "Nước đi {played_move} kiểm soát vị trí vô cùng xuất sắc.",
      "Rất chắc chắn! {played_move} mang lại sự ổn định mạnh mẽ cho thế trận.",
      "Bạn làm rất tốt khi chọn {played_move}. {best_move} có nhỉnh hơn chút xíu thôi.",
      "Sự nhạy bén rất đáng nể với {played_move}.",
      "Chênh lệch với {best_move} là cực nhỏ, {played_move} rất đáng mặt đại cao thủ.",
      "Tuyệt vời! Tuy không phải tuyệt đối, nhưng {played_move} là quá đủ để chiến thắng.",
      "Bạn quyết định rất bén ngọt với {played_move}.",
      "Nước cờ {played_move} này khiến thế trận của bạn trở nên quá vững.",
      "{played_move} cho thấy tư duy chiến thuật rất đáng nể của bạn.",
      "Đáng khen ngợi! Hầu hết mọi người cũng sẽ chọn {played_move} ở đây.",
      "Kỳ thủ chuyên nghiệp cũng rất hay sử dụng {played_move}.",
      "Nước cờ {played_move} cho thấy bạn hiểu rất rõ về ván này.",
      "Chỉ kém nước {best_move} vài centipawn, {played_move} thực sự là lựa chọn kim cương.",
      "Rất kiên nhẫn và sắc sảo, {played_move} thiết lập nền tảng vững chắc.",
      "Hay đi! Đối phương không dễ dàng tìm ra kế phá {played_move}.",
      "Chỉ những người am hiểu cờ mới đi {played_move} hiệu quả đến vậy.",
      "Hoàn thành xuất sắc nhiệm vụ ở vị trí này với {played_move}.",
      "Bình tĩnh nhưng đầy nguy hiểm, {played_move} đang làm đối thủ lo sợ.",
      "Rất điệu nghệ. {played_move} xử lý tốt áp lực.",
      "Bạn đã đánh giá đúng mức độ đe dọa và chọn {played_move} cực hay.",
      "{played_move} tỏ ra vô cùng cứng cáp.",
      "Rất đẹp mắt! {played_move} duy trì một cấu trúc ổn định.",
      "Tín hiệu tốt! Khả năng tính toán của bạn với {played_move} rất sâu.",
      "Tuyệt hảo! {played_move} thu hẹp rất tốt phạm vi của đối phương.",
      "{played_move} làm cho mọi thứ được kiểm soát tốt hơn.",
      "Đó là một nước rất cao! Sự khác biệt với {best_move} gần như không đáng kể.",
      "Thật sáng dạ khi ra quyết định {played_move} lúc này.",
      "Đối phương sẽ rất mệt mỏi với rào cản từ {played_move}.",
      "Làm tốt lắm. Nếu đi {best_move} thì tối đa hóa, nhưng {played_move} cũng đủ tiêu diệt địch.",
      "Bạn đang đánh bậtọi phân tích bằng trực giác tốt của {played_move}.",
      "Quá điêu luyện đi! {played_move} thể hiện bạn có bề dày kinh nghiệm.",
      "Xử lý vô cùng tinh gọn với {played_move}.",
      "Rất nhạy bén! Bạn chọn {played_move} cực kỳ hợp lý.",
      "Điều này chứng tỏ bạn đang ở trạng thái tập trung tốt: chọn được {played_move}.",
      "{played_move} mở ra những hướng tấn công rất thoáng.",
      "Không hề e ngại, {played_move} là biểu hiện của sự dũng cảm và chính xác.",
      "Một lựa chọn tuyệt tạc cho một tình huống rắc rối: {played_move}.",
      "Nước cờ {played_move} làm hài lòng mọi con mắt phê bình."
    ],
    MoveCategory.good: [
      "Một nước đi tốt. {played_move} hoàn toàn chấp nhận được.",
      "Bạn chơi an toàn với {played_move}. Nước {best_move} có phần mạo hiểm và sắc sảo hơn.",
      "Chấp nhận được! {played_move} duy trì lợi thế nhất định.",
      "Một bước đi khá. Tuy nhiên nếu tinh ý sẽ thấy {best_move} tốt hơn.",
      "Không tệ chút nào. {played_move} là một quyết định khá cơ bản.",
      "{played_move} khá ổn định, dẫu chưa phải nước mạnh nhất.",
      "Nước cờ {played_move} giữ vững trận địa cho bạn.",
      "Một nước cờ chắc chắn. Lựa chọn {played_move} không làm mất điểm.",
      "Bạn đi {played_move} cẩn trọng quá mức. Thử mạnh dạn cân nhắc {best_move} nhé.",
      "Làm tốt lắm. Nước {played_move} giúp giải quyết một số vấn đề trên bàn cờ.",
      "Hợp lý đấy! Dù vậy máy đánh giá {best_move} trội hơn một chút.",
      "{played_move} là nước đi có tính thực tế cao.",
      "Cơ bản và hiệu quả: {played_move}.",
      "Mọi thứ vẫn đang ổn thoả. Định hướng với {played_move} là có thể theo được.",
      "Đây là nước đi mang tính phong vị cờ người: {played_move}.",
      "Một quyết định tốt ở thời điểm này. {played_move} khá mạnh.",
      "Khá hay. Không thể trách móc {played_move} được.",
      "Dù máy khuyên {best_move}, nước {played_move} của bạn lại dễ hiểu và dễ chơi hơn.",
      "Bạn giải quyết tình hình bằng {played_move}. Như thế là quá đủ tốt rồi.",
      "Khá sáng suốt! Định hình được một thế trận rõ ràng với {played_move}.",
      "Nước cờ {played_move} thực thi khá tốt kế hoạch của bạn.",
      "Cứ bình tĩnh phát triển thế này với {played_move} là đủ chơi.",
      "Chơi vậy là rất chuẩn phong độ rồi bằng {played_move}.",
      "Lựa chọn hợp lý {played_move} để củng cố sức mạnh của mình.",
      "Một nước đi tuân thủ nguyên tắc với {played_move}.",
      "Tốt đấy! Bạn nhận ra những lợi thế nhỏ từ {played_move}.",
      "Có thể chưa xuất sắc tuyệt đối nhưng {played_move} vẫn đạt yêu cầu chuyên môn.",
      "An toàn và chắc chắn là tiêu chí hàng đầu của {played_move}.",
      "Giữ gìn mọi thứ gọn gàng với {played_move}.",
      "Khá khôn khéo. Tránh rủi ro bằng ván bài {played_move}.",
      "Không có gì phải nuối tiếc ở nước {played_move} cả.",
      "Từng bước đi tới thắng lợi, và {played_move} là một viên gạch vững bền.",
      "Đi {played_move} là cách không để tuột mất ván cờ này.",
      "Một lối chơi thực dụng mang lại kết quả tốt vơi {played_move}.",
      "Tuyệt. Giờ bạn chỉ cần củng cố đội hình sau nước {played_move}.",
      "Dễ dàng triển khai tiếp sau quyết định {played_move}.",
      "Bình tĩnh, nhịp nhàng. Nước {played_move} khá nghệ sĩ dẫu kém một tẹo so với {best_move}.",
      "Sự lựa chọn {played_move} rất đáng yêu và logic.",
      "Một mũi tên trúng khá nhiều đích nhỏ lẻ với {played_move}.",
      "{played_move} thật sự rất hợp lý với suy nghĩ chung."
    ],
    MoveCategory.inaccuracy: [
      "Hơi thiếu chính xác. Nước đi {played_move} bỏ lỡ mất một cơ hội nhỏ.",
      "Có lẽ bạn vội vàng với {played_move}. {best_move} sẽ tối ưu hơn.",
      "{played_move} là một nước đi không chuẩn xác. Mặc dù hậu quả chưa lớn trọng.",
      "Bạn nên xem xét kỹ hơn. Đáng nhẽ có thể đi {best_move} thay vì {played_move}.",
      "Nước {played_move} chưa thực sự phát huy hết sức mạnh của cờ bạn.",
      "Sơ suất nhỏ thôi! Tuy đi {played_move} chưa tối ưu, nhưng vẫn gượng vững được.",
      "Sẽ ngon ăn hơn nếu tìm ra {best_move}. Dù sao {played_move} làm mất vài lợi thế.",
      "Nước đi {played_move} là một nét việt vị nhẹ trong khâu tính toán.",
      "Hơi lệch nhịp! Nước cờ {played_move} làm mọi thứ chậm lại, thử thay bằng {best_move} nhé.",
      "Đáng tiếc! Nước cờ {played_move} là hòn đá cản đường sự trôi chảy của ván đấu.",
      "{played_move} mở ra vài kẽ hở không đáng có.",
      "Sự lựa chọn {played_move} là một nhịp nghỉ hơi không cần thiết lúc này.",
      "Bạn để lọt mất một biến mỏng nhưng sắc với {played_move}.",
      "Thiếu sót đáng tiếc. Giá như chọn {best_move} thì hay biết mấy thay vì {played_move}.",
      "Nên chú ý! Một chút lỏng lẻo đang bắt đầu từ {played_move}.",
      "Bỏ quên đi cơ hội chiếm ưu thế! Bạn vừa đi {played_move}.",
      "Một nước khá yếu, làm bạn chững lại mất một nhịp với {played_move}.",
      "{played_move} có chút vụng về ở tình cảnh này.",
      "Đây là lúc đáng phải tìm kiếm {best_move}, thay vì dễ dãi chấp nhận {played_move}.",
      "Bạn làm phức tạp hóa vấn đề mà hiệu quả lại thấp ở nước {played_move}.",
      "Sự thiển cận nhẹ đã dẫn tới lựa chọn {played_move} ở đây.",
      "Cần soi xét kỹ lưỡng hơn, bước {played_move} của bạn làm giảm bớt vài điểm quan vĩ vi mô.",
      "Không thảm hoạ, dẫu vậy nước đi {played_move} đánh rơi kha khá tài sản trên bàn.",
      "Trực giác của bạn làm việc không ổn ở nhịp đi {played_move} này.",
      "{played_move} thiếu một xíu sự sắc sảo cần có.",
      "Hơi bị động quá đáng khi đi {played_move}.",
      "Chệch quỹ đạo xíu rồi! Tại sao lại dấn thân vào {played_move} thế kia?",
      "Trạng thái thiếu tập trung dẫn tới nước cờ ngây thơ {played_move}.",
      "Có thể bạn quá cẩn trọng mà bỏ qua thời cơ và đi {played_move}.",
      "Nước cờ {played_move} quá thụ động.",
      "Một tiếng thở dài nhẹ. Nước cờ {played_move} kém một nhịp sâu sắc.",
      "Đi máy tính sẽ phát điên nếu con người cứ đi cờ kiểu {played_move} đó.",
      "{played_move} tỏ ra có chút bất hợp lý so với diễn biến.",
      "Sự kém chính xác nhẹ qua quyết định {played_move} đã làm trận thế nhạt đi một phân.",
      "Để mất lợi thế một cách lãng xẹt qua nước đi {played_move}.",
      "{played_move} hơi nửa vời, đáng lý cần tính dứt khoát hơn là {best_move}.",
      "Việc tính sót biến dẫn đến sự lỏng lẻo qua {played_move}.",
      "Thiếu lửa rồi. Bước {played_move} là một biểu hiện của sự nguội dần tính toán.",
      "Nước {played_move} không được sắc, đối phương sẽ bắt thóp dễ hơn.",
      "Với nước đi này ({played_move}), bạn đang tự làm mình mệt mỏi thêm."
    ],
    MoveCategory.mistake: [
      "Lỗi nặng! Bạn vừa ném đi bao nhiêu lợi thế bằng {played_move}.",
      "Một sai sót lớn! Đáng lẽ phải cân nhắc {best_move} ở thời điểm này.",
      "{played_move} là một nước đi tồi. Tình thế bây giờ trở nên rất căng.",
      "Ôi không, tại sao lại đi {played_move}? Bạn đáng nhẽ cần phòng thủ hoặc phản công bằng {best_move}.",
      "Quá sai lầm! Bạn vô tình đánh đổi quyền chủ động qua {played_move}.",
      "Bước ngoặt tệ hại! Cơ duyên ngàn vàng đã bay mất với {played_move}.",
      "Bạn vừa bước thẳng vào cạm bẫy với quyết định {played_move}.",
      "Hỏng chuyện! {played_move} làm cho đối phương lật ngược thế cờ quá dễ dàng.",
      "Đáng trách! Một sự tính toán sai lầm đã hiển hiện qua nước cờ {played_move}.",
      "Bạn dâng hiến cả một con bài chủ lực và thế trận qua {played_move}.",
      "Nước đi {played_move} đầy rủi ro và thiếu sự chuẩn bị kỹ lưỡng.",
      "Chắc bạn bối rối? {played_move} thật sự là một nước đi đáng buồn.",
      "Mất tập trung hoàn toàn! Bạn vừa để đối thủ tìm thấy kẽ hở lớn sau {played_move}.",
      "Trời ơi, nếu như tìm ra {best_move}, thay vì đi nước cờ sai lệch {played_move}...",
      "Khó đỡ! {played_move} để mặc hàng phòng thủ trong thế lung lay mạnh.",
      "Một đòn gậy đập lưng ông. Kế hoạch sụp đổ vì nước cờ {played_move}.",
      "Với {played_move}, hệ số điểm của bạn vừa tụt dốc không phanh.",
      "{played_move} là minh chứng của việc đọc bảng vị chưa tốt.",
      "Phá hỏng toàn bộ cục diện đẹp đẽ đã tạo! Chỉ vì {played_move}.",
      "Lời khuyên là hãy tỉnh táo hơn, lỗi lầm {played_move} thực sự đắt giá.",
      "Không ngờ bạn lại để sẩy chân ở {played_move}. Nó thật sự quá yếu.",
      "Hối tiếc! Nước {played_move} đã tạo nên một chuỗi sai phạm theo tầng.",
      "Đây là sự suy giảm sút phong độ đáng chú ý với sai trái ở {played_move}.",
      "Bị đối thủ ép đến nổi cuống cuồng tung ra bước đi dở tệ {played_move}.",
      "Chẳng ai ngờ một kỳ thủ lại mắc cái bẫy sơ đẳng với {played_move}.",
      "Vội vàng! Nước đi {played_move} đốt cháy hoàn toàn giai đoạn đang có.",
      "{played_move} giống như trao chiến thắng tước từ tay của bản thân đi vậy.",
      "Trắng tay! Bao nỗ lực tan biến sau một thoáng sai lầm {played_move}.",
      "Thật đau đầu, một nước tệ đến mức làm tổn thương điểm thi đấu: {played_move}.",
      "Rõ ràng {played_move} là một ảo tưởng vào một thế trận không có thật.",
      "Tại sao? Thay vì {best_move}, sự dại dột {played_move} lại chiếm hữu tâm trí.",
      "Không cứu vãn được cục diện móp méo do sự cố mang tên {played_move}.",
      "Hệt như một gáo nước lạnh tạt vào sự kiêu hãnh cờ vua: bạn đi {played_move}.",
      "Mọi thứ đảo lộn xộn, bạn đẩy tình huống đến tuyệt vọng bằng {played_move}.",
      "Thật đáng báo động! {played_move} châm ngòi cho hàng loạt hiểm hoạ rình rập.",
      "{played_move} chính xác là điểm chết của ván đấu này.",
      "Một sự yếu kém về mặt phân tích hiện lên ở nước {played_move}.",
      "Phung phí tài nguyên vô nghĩa qua {played_move}. Thật sai quá sai.",
      "Chưa nhìn thấu đòn đối phương đã hấp tấp chơi bước {played_move} này.",
      "Mời bạn uống một ly lãng quên cho cái sai {played_move} đáng bực này."
    ],
    MoveCategory.blunder: [
      "Trời đất, {played_move} là một sai lầm chí mạng! Nhẽ ra bạn phải đi {best_move} để cứu vãn tình hình, hoặc ít nhất là {alt_move_1}.",
      "Một pha dâng hiến không thể tin nổi! Hậu quả của {played_move} là thảm họa.",
      "Cạn lời! Nước cờ {played_move} là một Blunder đưa cổ vào máy chém.",
      "Thật điên rồ! Sao bạn có thể đi {played_move} trong trận mạc này? Nước {best_move} rõ mười mươi cơ mà.",
      "Mọi hy vọng đã bị giập tắt bởi cái tự thiêu mang tên {played_move}.",
      "Thảm họa cấp độ thảm hoạ! Nước đi {played_move} là điều tồi tệ nhất bạn có thể làm.",
      "Bạn biếu không luôn trận đấu cho đối thủ chỉ với một nước đi thiển cận {played_move}.",
      "Gục ngã hoàn toàn! Ngay ở nhịp độ quyết định, một trận động đất {played_move} xảy ra.",
      "Blunder kinh hoàng! Chỉ một cú {played_move} đã tống tiễn tất cả công sức xuống biển.",
      "Sự bế tắc của tâm trí đưa tới một thảm cảnh tên là {played_move}.",
      "Bạn đang tặng điểm miễn phí ư? Nước {played_move} là một sự ngớ ngẩn đến đáng sợ.",
      "Hãy tháo mặt nạ ra đi! Làm sao cao thủ lại để lỡ trận đồ rồi đi {played_move} được chứ.",
      "Trùm cuối của thất bại chính là đây: Nước đi thảm hại {played_move}.",
      "Bao nhiêu thế cờ đẹp, bạn đem bán sạch chỉ bằng {played_move}.",
      "Khó bào chữa. Nước cờ {played_move} là một viên đạn nã vào đầu quân vua phe bạn.",
      "Mù quáng! Sức sát thương của sự ngu ngốc {played_move} là quá khủng khiếp.",
      "Kỳ thủ nào cũng sẽ khóc thét khi nhìn thấy mình đánh ra {played_move} sau ván.",
      "Đây không phải là sai lầm nữa, đây là sự đầu hàng vô điều kiện bằng {played_move}.",
      "Ác mộng thực sự! Hàng triệu ván cờ, chửa thấy ai tự kết liễu nhanh bằng {played_move}.",
      "Tệ hại nhất có thể! Vua của bạn đang than khóc vì pha chưởng tự huỷ {played_move}.",
      "Bạn có chắc đây không phải trượt chuột máy tính? {played_move} là thảm thương vô địch.",
      "Nỗi nhục nhã của bàn cờ là đây: Đem dâng tặng lợi thế 100% bằng {played_move}.",
      "Sự thiển ý đã lên đến mức cao trào. Rớt đài bằng {played_move}.",
      "Nhắm mắt đánh bừa cũng không ra được đường diệt binh nhanh như {played_move}.",
      "Còn gì nữa đâu mà khóc với sầu! {played_move} bóp nghẹt mọi tương lai.",
      "Hãy reset não ngay! Một blunder khổng lồ như {played_move} không nên tái diễn.",
      "Thằng ngốc cũng có thể thấy {best_move} mạnh hơn, xin chia buồn cùng con ngáo {played_move}.",
      "Nước đi phế vật {played_move} biến lợi thế 100 điểm về âm vô cực.",
      "Tai nạn giao thông trên bàn cờ vua chính là cú vấp {played_move} kinh hoàng.",
      "Ôi chao! Sao bạn dám nướng trọn sự rèn luyện vào trong ngọn lửa {played_move} ngu dốt kia.",
      "Tuyệt vọng! {played_move} giật mìn nổ tung kho tàng chiến thuật của bạn.",
      "Thật xót xa! Không ai còn có thể vực dậy nổi sau sai đòn tử thần {played_move}.",
      "Đi thẳng vào lòng đất, dập mộ chôn thây với quyết định hãm hại {played_move}.",
      "Blunder bự bự chà bá lửa! Phung phí cả một đời anh tài vào nước cờ lụi bại {played_move}.",
      "Nếu cờ vua có cái gọi là tự sát cấp độ 1, thì đó là việc bạn làm bằng nước {played_move}.",
      "Hoảng loạn đến điên khùng rồi hử? Thử hỏi bộ não bạn chạy đâu khi rập rờn bước {played_move}?",
      "Trượt dốc không phanh thẳng vào hư vô với thất bại toàn tập mang số hiệu {played_move}.",
      "Bạn định tự đưa cổ vào thòng lọng ư? Tuyển chọn {played_move} đã làm đúng điều đó.",
      "Kéo sập cả vương quốc bằng một sai lầm không thuốc chữa {played_move}.",
      "Muốn chửi thề nhưng không còn hơi nữa. Ván bài đổ vỡ từ {played_move} ngu ngơ này rồi."
    ],
  };

  static String generate(MoveCategory category, String played, String best, [String? alt1, String? alt2]) {
    final templates = _templates[category]!;
    final template = templates[_random.nextInt(templates.length)];
    
    return template
        .replaceAll('{played_move}', played)
        .replaceAll('{best_move}', best)
        .replaceAll('{alt_move_1}', alt1 ?? best)
        .replaceAll('{alt_move_2}', alt2 ?? best);
  }
}
